# Generated by Django 4.0 on 2022-01-08 06:52

from django.db import migrations
from django.conf import settings
import os
from django.core.management.sql import emit_post_migrate_signal


def set_site_name(apps, schema_migration):
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    SiteModel = apps.get_model('sites', 'Site')
    domain = os.environ.get('SITE_DOMAIN')

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )


class Migration(migrations.Migration):
    dependencies = [
        ('bugtracker', '0002_auto_20220106_2155'),
    ]

    operations = [
        migrations.RunPython(set_site_name)
    ]
